version: '2.4'

services:
  target:
    build: .
    platform: linux/amd64
    privileged: true
    stdin_open: true
    ports:
      - "8080:80"
  # exploit:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.exploit
  #   stdin_open: true
  #   tty: true
